### ISSUE TITLE
AssertionError does not abort the job on the cluster

### ISSUE THREAD

**Issue by mtelewa** [hannes-holey/hans#20]
**Sumary:**

When encountered with:
```'bash
AssertionError: Density too high for Dowson-Higginson EOS
```
line 46 in the material.py, the job continued using the resources on the cluster until it get aborted as it reached time limit.

**Expected Outcome**
Abort job when assertion error is encountered

**HANS version**
0.0.20

**Comment by hannes-holey** [comment]
Fixed in version 0.0.21. MPI processes are aborted now with errorcode 1 by default, which properly ends jobs on HPC-clusters. Tested on bwunicluster (SLURM) and NEMO (MOAB).
